name: Extract ZIP in Repo

on:
  push:
    branches:
      - main  # Change 'main' to your default branch if different

jobs:
  extract:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Extract ZIP File
        run: |
          unzip website.zip -d extracted
          mv extracted/* .
          rm -rf extracted website.zip

      - name: Commit Extracted Files
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add .
          git commit -m "Extracted ZIP files"
          git push
